version: "3"
services:
    mariadb:
        image: mariadb
        hostname: mariadb
        environment:
          - MYSQL_ROOT_PASSWORD=password
        ports:
          - 3306:3306
        networks:
            cindernet:
                ipv4_address: 172.49.49.2
        volumes:
            #- ./data/db-data:/var/lib/mysql
            #- ./data/db-logs:/var/log
            - ./mariadb/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d

    rabbitmq:
        image: rabbitmq
        ports:
          - 5672:5672
        hostname: rabbitmq
        networks:
            cindernet:
                ipv4_address: 172.49.49.3

    keystone:
        image: test:keystone
        depends_on:
          - mariadb
        ports:
          - 5000:5000
          - 35357:35357
        hostname: keystone
        networks:
            cindernet:
                ipv4_address: 172.49.49.4
        extra_hosts:
            - "mariadb:172.49.49.2"
            - "rabbitmq:172.49.49.3"
            - "keystone:172.49.49.4"
            - "cinder-api:172.49.49.5"
            - "cinder-scheduler:172.49.49.6"
            - "glance-api:172.49.49.7"
            - "glance-registry:172.49.49.8"
            - "nova-api:172.49.49.9"
            - "nova-consoleauth:172.49.49.10"
            - "nova-scheduler:172.49.49.11"
            - "nova-conductor:172.49.49.12"
            - "nova-novncproxy:172.49.49.13"
            - "nova-compute:172.49.49.14"

        volumes:
          - ./keystone:/etc/keystone_cp
          - ./fresh:/etc/fresh:ro
        #entrypoint: /etc/keystone_cp/keystone.sh 
        command: ["/etc/fresh/wait-for-it.sh", "mariadb:3306", "-t", "60", "--", "/etc/keystone_cp/keystone.sh"]
        container_name: keystone


    cinder-api:
        image: cinder
        hostname: cinder-api
        volumes:
            - ./cinder/etc/:/etc/cinder
            - ./cinder/init-script/:/init-script/
            - ./fresh:/etc/fresh:ro
        networks:
            cindernet:
                ipv4_address: 172.49.49.5
        ports:
            - 8776:8776
        depends_on:
          - mariadb
        extra_hosts:
            - "mariadb:172.49.49.2"
            - "rabbitmq:172.49.49.3"
            - "keystone:172.49.49.4"
            - "cinder-api:172.49.49.5"
            - "cinder-scheduler:172.49.49.6"
            - "glance-api:172.49.49.7"
            - "glance-registry:172.49.49.8"
            - "nova-api:172.49.49.9"
            - "nova-consoleauth:172.49.49.10"
            - "nova-scheduler:172.49.49.11"
            - "nova-conductor:172.49.49.12"
            - "nova-novncproxy:172.49.49.13"
            - "nova-compute:172.49.49.14"

        environment:
            - INIT_DB=true
#        command: sh /init-script/cinder-api.sh
        # Wait for the database to come online, so db sync doesn't fail repeatedly.
        command: ["/etc/fresh/wait-for-it.sh", "mariadb:3306", "-t", "60", "--", "/init-script/cinder-api.sh"]

    cinder-scheduler:
        image: cinder
        hostname: cinder-scheduler
        volumes:
            - ./cinder/etc/:/etc/cinder
            - ./fresh:/etc/fresh:ro
        networks:
            cindernet:
                ipv4_address: 172.49.49.6
        depends_on:
          - mariadb
          - rabbitmq
          - cinder-api
        extra_hosts:
            - "mariadb:172.49.49.2"
            - "rabbitmq:172.49.49.3"
            - "keystone:172.49.49.4"
            - "cinder-api:172.49.49.5"
            - "cinder-scheduler:172.49.49.6"
            - "glance-api:172.49.49.7"
            - "glance-registry:172.49.49.8"
            - "nova-api:172.49.49.9"
            - "nova-consoleauth:172.49.49.10"
            - "nova-scheduler:172.49.49.11"
            - "nova-conductor:172.49.49.12"
            - "nova-novncproxy:172.49.49.13"
            - "nova-compute:172.49.49.14"

        restart: on-failure
        command: ["/etc/fresh/wait-for-it.sh", "cinder-api:8776", "-t", "60", "--", "cinder-scheduler"]


    cinder-volume:
        image: cinder-lvm
        hostname: cinder-lvm
        privileged: true
        volumes:
            - ./cinder/etc/:/etc/cinder
            - /dev/:/dev/
            - /run/:/run/:shared
            - /etc/localtime:/etc/localtime:ro
            - /lib/modules:/lib/modules:ro
            - ./cinder/init-script/:/init-script/
            - ./fresh:/etc/fresh:ro
        depends_on:
          - cinder-scheduler
        ports:
            - 3260:3260
        extra_hosts:
            - "mariadb:172.49.49.2"
            - "rabbitmq:172.49.49.3"
            - "keystone:172.49.49.4"
            - "cinder-api:172.49.49.5"
            - "cinder-scheduler:172.49.49.6"
            - "glance-api:172.49.49.7"
            - "glance-registry:172.49.49.8"
            - "nova-api:172.49.49.9"
            - "nova-consoleauth:172.49.49.10"
            - "nova-scheduler:172.49.49.11"
            - "nova-conductor:172.49.49.12"
            - "nova-novncproxy:172.49.49.13"
            - "nova-compute:172.49.49.14"

        network_mode: "host"
        restart: on-failure
        #command: bash -c "sleep 5 && /usr/sbin/tgtd && cinder-volume -d"
        command: ["/etc/fresh/wait-for-it.sh", "cinder-api:8776", "-t", "60", "--", "/init-script/cinder-volume.sh"]

    glance-api:
        image: test:glance
        hostname: glance-api
        volumes:
            - ./glance/etc/:/etc/glance
            - ./fresh:/etc/fresh:ro
            - ./glance/init-script/:/init-script/
        networks:
            cindernet:
                ipv4_address: 172.49.49.7
        ports:
          - 9292:9292
        environment:
            - INIT_DB=true
        depends_on:
          - mariadb
          - rabbitmq
        extra_hosts:
            - "mariadb:172.49.49.2"
            - "rabbitmq:172.49.49.3"
            - "keystone:172.49.49.4"
            - "cinder-api:172.49.49.5"
            - "cinder-scheduler:172.49.49.6"
            - "glance-api:172.49.49.7"
            - "glance-registry:172.49.49.8"
            - "nova-api:172.49.49.9"
            - "nova-consoleauth:172.49.49.10"
            - "nova-scheduler:172.49.49.11"
            - "nova-conductor:172.49.49.12"
            - "nova-novncproxy:172.49.49.13"
            - "nova-compute:172.49.49.14"

        restart: on-failure
        command: ["/etc/fresh/wait-for-it.sh", "mariadb:3306", "-t", "60", "--", "/init-script/glance-api.sh"]
#        command: ["/etc/fresh/wait-for-it.sh", "mariadb:3306", "-t", "60", "--", "/etc/fresh/idle.sh"]


    glance-registry:
        image: test:glance
        hostname: glance-registry
        volumes:
            - ./glance/etc/:/etc/glance
            - ./fresh:/etc/fresh:ro
            - ./glance/init-script/:/init-script/
        networks:
            cindernet:
                ipv4_address: 172.49.49.8
        depends_on:
          - mariadb
          - rabbitmq
          - glance-api
        extra_hosts:
            - "mariadb:172.49.49.2"
            - "rabbitmq:172.49.49.3"
            - "keystone:172.49.49.4"
            - "cinder-api:172.49.49.5"
            - "cinder-scheduler:172.49.49.6"
            - "glance-api:172.49.49.7"
            - "glance-registry:172.49.49.8"
            - "nova-api:172.49.49.9"
            - "nova-consoleauth:172.49.49.10"
            - "nova-scheduler:172.49.49.11"
            - "nova-conductor:172.49.49.12"
            - "nova-novncproxy:172.49.49.13"
            - "nova-compute:172.49.49.14"

        restart: on-failure
        command: ["/etc/fresh/wait-for-it.sh", "glance-api:9292", "-t", "60", "--", "/init-script/glance-registry.sh"]



    nova-api:
        image: test:nova
        hostname: nova-api
        privileged: true
        volumes:
            - ./nova/etc/:/etc/nova:ro
            - ./fresh:/etc/fresh:ro
            - ./nova/init-script/:/init-script/
        networks:
            cindernet:
                ipv4_address: 172.49.49.9
        ports:
          - 8774:8774
          - 8775:8775
        depends_on:
          - mariadb
          - rabbitmq
        extra_hosts:
            - "mariadb:172.49.49.2"
            - "rabbitmq:172.49.49.3"
            - "keystone:172.49.49.4"
            - "cinder-api:172.49.49.5"
            - "cinder-scheduler:172.49.49.6"
            - "glance-api:172.49.49.7"
            - "glance-registry:172.49.49.8"
            - "nova-api:172.49.49.9"
            - "nova-consoleauth:172.49.49.10"
            - "nova-scheduler:172.49.49.11"
            - "nova-conductor:172.49.49.12"
            - "nova-novncproxy:172.49.49.13"
            - "nova-compute:172.49.49.14"
        restart: on-failure
        command: ["/etc/fresh/wait-for-it.sh", "mariadb:3306", "-t", "60", "--", "/init-script/nova-api.sh"]
        environment:
            - INIT_DB=true


    nova-consoleauth:
        image: test:nova
        hostname: nova-consoleauth
        privileged: true
        volumes:
            - ./nova/etc/:/etc/nova:ro
            - ./fresh:/etc/fresh:ro
            - ./nova/init-script/:/init-script/
        networks:
            cindernet:
                ipv4_address: 172.49.49.10
        depends_on:
          - mariadb
          - rabbitmq
          - nova-api
        extra_hosts:
            - "mariadb:172.49.49.2"
            - "rabbitmq:172.49.49.3"
            - "keystone:172.49.49.4"
            - "cinder-api:172.49.49.5"
            - "cinder-scheduler:172.49.49.6"
            - "glance-api:172.49.49.7"
            - "glance-registry:172.49.49.8"
            - "nova-api:172.49.49.9"
            - "nova-consoleauth:172.49.49.10"
            - "nova-scheduler:172.49.49.11"
            - "nova-conductor:172.49.49.12"
            - "nova-novncproxy:172.49.49.13"
            - "nova-compute:172.49.49.14"
        restart: on-failure
        command: ["/etc/fresh/wait-for-it.sh", "nova-api:8774", "-t", "120", "--", "/init-script/nova-consoleauth.sh"]

    nova-scheduler:
        image: test:nova
        hostname: nova-scheduler
        privileged: true
        volumes:
            - ./nova/etc/:/etc/nova:ro
            - ./fresh:/etc/fresh:ro
            - ./nova/init-script/:/init-script/
        networks:
            cindernet:
                ipv4_address: 172.49.49.11
        depends_on:
          - mariadb
          - rabbitmq
          - nova-api
        extra_hosts:
            - "mariadb:172.49.49.2"
            - "rabbitmq:172.49.49.3"
            - "keystone:172.49.49.4"
            - "cinder-api:172.49.49.5"
            - "cinder-scheduler:172.49.49.6"
            - "glance-api:172.49.49.7"
            - "glance-registry:172.49.49.8"
            - "nova-api:172.49.49.9"
            - "nova-consoleauth:172.49.49.10"
            - "nova-scheduler:172.49.49.11"
            - "nova-conductor:172.49.49.12"
            - "nova-novncproxy:172.49.49.13"
            - "nova-compute:172.49.49.14"

        restart: on-failure
        command: ["/etc/fresh/wait-for-it.sh", "nova-api:8774", "-t", "120", "--", "/init-script/nova-scheduler.sh"]

    nova-conductor:
        image: test:nova
        hostname: nova-conductor
        privileged: true
        volumes:
            - ./nova/etc/:/etc/nova:ro
            - ./fresh:/etc/fresh:ro
            - ./nova/init-script/:/init-script/
        networks:
            cindernet:
                ipv4_address: 172.49.49.12
        depends_on:
          - mariadb
          - rabbitmq
          - nova-api
        extra_hosts:
            - "mariadb:172.49.49.2"
            - "rabbitmq:172.49.49.3"
            - "keystone:172.49.49.4"
            - "cinder-api:172.49.49.5"
            - "cinder-scheduler:172.49.49.6"
            - "glance-api:172.49.49.7"
            - "glance-registry:172.49.49.8"
            - "nova-api:172.49.49.9"
            - "nova-consoleauth:172.49.49.10"
            - "nova-scheduler:172.49.49.11"
            - "nova-conductor:172.49.49.12"
            - "nova-novncproxy:172.49.49.13"
            - "nova-compute:172.49.49.14"

        restart: on-failure
        command: ["/etc/fresh/wait-for-it.sh", "nova-api:8774", "-t", "120", "--", "/init-script/nova-conductor.sh"]

    nova-novncproxy:
        image: test:nova
        hostname: nova-novncproxy
        privileged: true
        volumes:
            - ./nova/etc/:/etc/nova:ro
            - ./fresh:/etc/fresh:ro
            - ./nova/init-script/:/init-script/
        networks:
            cindernet:
                ipv4_address: 172.49.49.13
        ports:
            - 6080:6080
        depends_on:
          - mariadb
          - rabbitmq
          - nova-api
        extra_hosts:
            - "mariadb:172.49.49.2"
            - "rabbitmq:172.49.49.3"
            - "keystone:172.49.49.4"
            - "cinder-api:172.49.49.5"
            - "cinder-scheduler:172.49.49.6"
            - "glance-api:172.49.49.7"
            - "glance-registry:172.49.49.8"
            - "nova-api:172.49.49.9"
            - "nova-consoleauth:172.49.49.10"
            - "nova-scheduler:172.49.49.11"
            - "nova-conductor:172.49.49.12"
            - "nova-novncproxy:172.49.49.13"
            - "nova-compute:172.49.49.14"

        restart: on-failure
        command: ["/etc/fresh/wait-for-it.sh", "nova-api:8774", "-t", "120", "--", "/init-script/nova-novncproxy.sh"]

    nova-compute:
        image: test:nova
        hostname: nova-compute
        privileged: true
        volumes:
            - ./nova/etc/:/etc/nova
            - ./fresh:/etc/fresh:ro
            - ./nova/init-script/:/init-script/
        networks:
            cindernet:
                ipv4_address: 172.49.49.14
        depends_on:
          - mariadb
          - rabbitmq
          - nova-api
        extra_hosts:
            - "mariadb:172.49.49.2"
            - "rabbitmq:172.49.49.3"
            - "keystone:172.49.49.4"
            - "cinder-api:172.49.49.5"
            - "cinder-scheduler:172.49.49.6"
            - "glance-api:172.49.49.7"
            - "glance-registry:172.49.49.8"
            - "nova-api:172.49.49.9"
            - "nova-consoleauth:172.49.49.10"
            - "nova-scheduler:172.49.49.11"
            - "nova-conductor:172.49.49.12"
            - "nova-novncproxy:172.49.49.13"
            - "nova-compute:172.49.49.14"

        restart: on-failure
#        command: ["/etc/fresh/wait-for-it.sh", "nova-api:8774", "-t", "120", "--", "/init-script/nova-compute.sh"]
        command: ["/etc/fresh/wait-for-it.sh", "nova-api:8774", "-t", "120", "--", "/etc/fresh/idle.sh"]


    client:
        image: test:client
        hostname: client
        depends_on:
            - keystone
        networks:
            cindernet:
                ipv4_address: 172.49.49.20
        extra_hosts:
            - "mariadb:172.49.49.2"
            - "rabbitmq:172.49.49.3"
            - "keystone:172.49.49.4"
            - "cinder-api:172.49.49.5"
            - "cinder-scheduler:172.49.49.6"
            - "glance-api:172.49.49.7"
            - "glance-registry:172.49.49.8"
            - "nova-api:172.49.49.9"
            - "nova-consoleauth:172.49.49.10"
            - "nova-scheduler:172.49.49.11"
            - "nova-conductor:172.49.49.12"
            - "nova-novncproxy:172.49.49.13"
            - "nova-compute:172.49.49.14"

        volumes:
          - ./client:/etc/client
          - ./fresh:/etc/fresh:ro
        container_name: client
        restart: always
        command: ["./etc/fresh/wait-for-it.sh", "keystone:5000", "-t", "60", "--", "./etc/client/client.sh"]
        environment:
            - INIT_GLANCE=true
            - INIT_NOVA=true
            - INIT_CINDER=true



networks:
    cindernet:
        driver: bridge
        ipam:
            driver: default
            config:
            -
              subnet: 172.49.49.0/24
